### ISSUE TITLE
Possible null pointer in utils

### ISSUE THREAD

**Issue by Valeriooooh** [Marinho3104/Spyke_BlockChain#1]
In the utils::get_file_data() function you don't check if the file exists, which can cause a null reference to a file.

Actually I am just going to mention that this project should be rewritten in **Rust** for it's correctness and memory management strategies. Since rust uses a powerful compiler that checks your code for possible runtime errors

 For example instead of returning a File pointer we return a result that can be a value(`Ok(&File)`) or `None` , and it encourages the developer to prevent possible failures in the runtime, by using a match operator.

**Comment by Marinho3104** [comment]
Thanks for the issue. After carefully thinking about your idea of switching to rust, i realise that i dont give a damn about rust. I can tell by your comment that you dont really get the point of the function in question. This function returns the content of a specific file not the File Pointer of it. But anyways the issue is solved and life goes on. C/C++ forever
